### PR TITLE
added support for reading raw RGB 16+16+16

### PR DESCRIPTION
**Pull request by isenberg**
Currently as RGB input format only RGBA 10+10+10+2 bits is supported which can't be written by most open source tools due to the difference in depth for the alpha channel compared to the RGB channels.

This change adds reading support for RGB 16+16+16 bits which is a more frequently used format, for example using ImageMagick:

magick infile.tif -depth 16 RBG:outfile.raw

To enable reading RGB 16+16+16: -a 13
to use existing RGBA 10+10+10+2 code: -a 5

Disadvantage of this quick hack: Internally it still uses the 10+10+10+2 format for storage, which means the lower 6 bits of each channel are ignored.

### CODE REVIEW

**Comment by gregbenz** [comment]
Might be worth having the tool issue a notice that the 16-bit input will be degraded to 10-bit, as this would not be suitable precision for data encoded with a linear EOTF.

**Comment by isenberg** [comment]
Greg, I wondered if higher intensity resolution is possible without too much change, but as currently the only other possible RGB input is RGBA 10+10+10+2 bits, it's at least not worse. I would also be fine with using YUV input which is supported, but couldn't find an open source tool offering that very bit-format accepted here.

**Comment by gregbenz** [comment]
Would 16-bit half float meet your needs? That would be high quality and enable linear encoding too. https://github.com/google/libultrahdr/issues/279. Perhaps that one update might solve both concerns.

Or do you need a need for 16-bit integer just for file format support?

**Comment by isenberg** [comment]
Yes, half-float rgb 16+16+16 or rgba 16+16+16+16 would work as well as that can also be written by ImageMagick or other tools. Example:
magick infile.tif -depth 16 -define quantum:format=floating-point RGBA:outfile.raw

I cleaned up my patch regarding comments now and added a note to the -h output about the 16 to 10 conversion.

**Comment by cgohlke** [comment]
My understanding that the `32bppRGBA1010102` format is not only about storage (that is easy to achieve with bit operations), but the color transfer must be "Hybrid log gamma" or "Perceptual Quantizer", not linear. No?

**Comment by gregbenz** [comment]
That format is just raw numbers, no headers. The EOTF is specified separately to libultra (such as via command line flags with the demo app), so you should be able to encode and use linear with any supported raw input. 

Linear is one of the supported input options. We just need a higher precision input like half float in order to avoid quantization error that would likely occur with a linear EOTF if using 10-bit integer precision.

**Comment by cgohlke** [comment]
Encoding linear `32bppRGBA1010102` succeeds for me but fails the roundtrip to linear `64bppRGBAHalfFloat`. The output looks like a color transfer function has been applied. I should double-check my code.

From the decoder documentation:

https://github.com/google/libultrahdr/blob/57247bf31e9c969d74d9d4da3b99d2bd7f6c454f/ultrahdr_api.h#L626-L630

**Comment by ram-mohan** [comment]
@isenberg some changes that were made are reverted in later commits. May be you can squash all the changes to a single commit and do a force push. This will reduce the amount of changes to go through. Further image magick already has a coder for [ultrahdr](https://github.com/ImageMagick/ImageMagick/commit/8a83a2bb40c2c0b7446c15d566d0a958742290f5), with that in context may be this change is not needed?

**Comment by cgohlke** [comment]
> fails the roundtrip to linear 64bppRGBAHalfFloat

Apologies. That actually works. It's the decoding to sRGB `32bppRGBA8888` that produces unexpected results:

UHDR encoded from linear RGBA1010102: uhdr
Expected output similar to this: expected

Anyway, this probably doesn't belong in this issue.

**Comment by isenberg** [comment]
>  Further image magick already has a coder for [ultrahdr](https://github.com/ImageMagick/ImageMagick/commit/8a83a2bb40c2c0b7446c15d566d0a958742290f5), with that in context may be this change is not needed?

@cgohlke : That replaces my rgb16 patch indeed! I wasn't aware of that support in ImageMagick and will use that now.

Canceling my pull request...

**Comment by ram-mohan** [comment]
> UHDR encoded from linear RGBA1010102: uhdr Expected output similar to this: expected
> 
> Anyway, this probably doesn't belong in this issue.

@cgohlke @gregbenz I would like to know few more details regarding this. So the input is 32bpp rgb1010102. From the aforth mentioned discussions I am assuming this is constructed by normalizing the rgb64 half float to 0-1 and then mapping it to 1024. Color transfer characteristics set to linear. Can you also tell me the peak luminance. For hlg it is 1000 nits and for PQ it is 10000 nits.

**Comment by ram-mohan** [comment]
> replaces

@isenberg Please let me how i can help if you are facing any issue. Thanks

**Comment by isenberg** [comment]
> @isenberg Please let me how i can help if you are facing any issue. Thanks

@ram-mohan , currently building it with --with-uhdr and trying out...

**Comment by isenberg** [comment]
> > replaces
> 
> @isenberg Please let me how i can help if you are facing any issue. Thanks

Works fine! Great to see how ImageMagick now can write UHDR JPG with gain map using the libultrahdr from here.

In case others searching for the topic like try, build instructions: https://github.com/ImageMagick/ImageMagick/commit/4b85373fcd4de75118c0bb62266b66f8245906ec

Important on macOS with brew is to prepend the cmake with the following to use only libjpeg-turbo which replaces libjpeg: CFLAGS="-Iopt/homebrew/opt/libjpeg-turbo/include" LDFLAGS="-L/opt/homebrew/opt/libjpeg-turbo/lib"

In case

**Comment by ram-mohan** [comment]
> > > replaces
> > 
> > 
> > @isenberg Please let me how i can help if you are facing any issue. Thanks
> 
> Works fine! Great to see how ImageMagick now can write UHDR JPG with gain map using the libultrahdr from here.
> 
> In case others searching for the topic like try, build instructions: [ImageMagick/ImageMagick@4b85373](https://github.com/ImageMagick/ImageMagick/commit/4b85373fcd4de75118c0bb62266b66f8245906ec)
> 
> Important on macOS with brew is to prepend the cmake with the following to use only libjpeg-turbo which replaces libjpeg: CFLAGS="-Iopt/homebrew/opt/libjpeg-turbo/include" LDFLAGS="-L/opt/homebrew/opt/libjpeg-turbo/lib"
> 
> In case

@isenberg All those things are no longer required.

1. install libjpeg (some thing like brew install jpeg-turbo / sudo apt install -y libjpeg-dev)
2. install libultrahdr
```
   git clone https://github.com/google/libultrahdr.git && cd libultrahdr && mkdir build && cd build
   cmake -G "Unix Makefiles" ../
   make
   sudo make install
```
3. clone image magick and configure with uhdr enabled
```
   git clone https://github.com/ImageMagick/ImageMagick.git && cd ImageMagick && mkdir build && cd build
   ../configure --with-uhdr && make
```

**Comment by isenberg** [comment]
For further details about ImageMagick and UltraHDR I see #7198 is best.

**Pull request closed without merging**
